# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

SOLUTION:

In [1]:
import numpy as np

In [5]:
arr = np.arange(2, 51, 3)
print(arr)
print(type(arr))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

SOLUTION:

In [14]:
list1 = []
list2 = []
for i in range(5):
    element = int(input())
    list1.append(element)
for i in range(5):
    element = int(input())
    list2.append(element)
print(list1)
print(list2)

22
35
65
34
21
25
56
76
58
98
[22, 35, 65, 34, 21]
[25, 56, 76, 58, 98]


In [15]:
arr1 = np.array(list1)
arr2 = np.array(list2)
res_arr = np.concatenate((arr1, arr2))
print(res_arr)

[22 35 65 34 21 25 56 76 58 98]


In [19]:
sorted_arr = np.sort(res_arr)
print(sorted_arr)

[21 22 25 34 35 56 58 65 76 98]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

SOLUTION:

In [21]:
array = np.array([[2, 3, 5], [5, 6, 7]])
print(array.shape)
print(array.size)

(2, 3)
6


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

SOLUTION:

In [31]:
arr_1D = np.array([1, 2, 3, 4, 5, 6])
print(arr_1D.shape)
arr_2D = np.expand_dims(arr_1D, axis=0)
print(arr_2D)
print(arr_2D.shape)

(6,)
[[1 2 3 4 5 6]]
(1, 6)


In [30]:
arr_2D = arr_1D[np.newaxis]
print(arr_2D)
print(arr_2D.shape)

[[1 2 3 4 5 6]]
(1, 6)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

SOLUTION:

In [37]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr2 = np.arange(10, 19).reshape(3,3)
print()
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [38]:
np.vstack((arr, arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
np.hstack((arr, arr2))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

# Questions 6:
How to get unique items and counts of unique items?

SOLUTION:

In [40]:
arr = np.array([[1, 4, 5], [2, 3 , 5], [4, 2, 1]])
print(arr)

[[1 4 5]
 [2 3 5]
 [4 2 1]]


In [44]:
uarr, counts = np.unique(arr, return_counts=True)
print(uarr)
print(counts)

[1 2 3 4 5]
[2 2 1 2 2]
